import tkinter as tk
import tkinter.messagebox as mg
window=tk.Tk()
window.title("calculator")
frame = tk.Frame(master=window,bg="gray",width=50)
frame.pack()
entry = tk.Entry(master=frame, relief=tk.RAISED, borderwidth=20, width=50)
entry.grid(row=0, column=3)
def no(n):
    entry.insert(tk.END,n)
def clear():
    entry.delete(0,tk.END)
def equal():
    try:
        y = str(eval(entry.get()))
        entry.delete(0, tk.END)
        entry.insert(0, y)
    except:
        mg.showinfo("error")
button0=tk.Button(master=frame,text="0",width=5,command=lambda:no(0))
button0.grid(row=2,column=1,padx=5,pady=5)
button1=tk.Button(master=frame,text="1",width=5,command=lambda:no(1))
button1.grid(row=2,column=2,padx=5,pady=5)
button2=tk.Button(master=frame,text="2",width=5,command=lambda:no(2))
button2.grid(row=2,column=3,padx=5,pady=5)
button3=tk.Button(master=frame,text="3",width=5,command=lambda:no(3))
button3.grid(row=2,column=4,padx=5,pady=5)
button4=tk.Button(master=frame,text="4",width=5,command=lambda:no(4))
button4.grid(row=2,column=5,padx=5,pady=5)
button5=tk.Button(master=frame,text="5",width=5,command=lambda:no(5))
button5.grid(row=3,column=1,padx=5,pady=5)
button6=tk.Button(master=frame,text="6",width=5,command=lambda:no(6))
button6.grid(row=3,column=2,padx=5,pady=5)
button7=tk.Button(master=frame,text="7",width=5,command=lambda:no(7))
button7.grid(row=3,column=3,padx=5,pady=5)
button8=tk.Button(master=frame,text="8",width=5,command=lambda:no(8))
button8.grid(row=3,column=4,padx=5,pady=5)
button9=tk.Button(master=frame,text="9",width=5,command=lambda:no(9))
button9.grid(row=3,column=5,padx=5,pady=5)
but1=tk.Button(master=frame,text="+",width=5,command=lambda:no("+"))
but1.grid(row=4,column=1,padx=5,pady=5)
but2=tk.Button(master=frame,text="-",width=5,command=lambda:no("-"))
but2.grid(row=4,column=2,padx=5,pady=5)
but3=tk.Button(master=frame,text="*",width=5,command=lambda:no("*"))
but3.grid(row=4,column=3,padx=5,pady=5)
but4=tk.Button(master=frame,text="/",width=5,command=lambda:no("/"))
but4.grid(row=4,column=4,padx=5,pady=5)
but5=tk.Button(master=frame,text="%",width=5,command=lambda:no("%"))
but5.grid(row=4,column=5,padx=5,pady=5)
button01=tk.Button(master=frame,text="(",width=5,command=lambda:no("("))
button01.grid(row=5,column=1,padx=5,pady=5)
button02=tk.Button(master=frame,text=")",width=5,command=lambda:no(")"))
button02.grid(row=5,column=2,padx=5,pady=5)
button03=tk.Button(master=frame,text=".",width=5,command=lambda:no("."))
button03.grid(row=5,column=4,padx=5,pady=5)
button04=tk.Button(master=frame,text="{",width=5,command=lambda:no("{"))
button04.grid(row=6,column=1,padx=5,pady=5)
button05=tk.Button(master=frame,text="}",width=5,command=lambda:no("}"))
button05.grid(row=6,column=2,padx=5,pady=5)
button06=tk.Button(master=frame,text="]",width=5,command=lambda:no("]"))
button06.grid(row=6,column=4,padx=5,pady=5)
button07=tk.Button(master=frame,text="[",width=5,command=lambda:no("["))
button07.grid(row=6,column=5,padx=5,pady=5)
button08=tk.Button(master=frame,text="~",width=5,command=lambda:no("~"))
button08.grid(row=5,column=5,padx=5,pady=5)
but6=tk.Button(master=frame,text="clear",width=5,command=clear)
but6.grid(row=5,column=3,padx=5,pady=5)
but7=tk.Button(master=frame,text="=",width=5,command=equal)
but7.grid(row=6,column=3,padx=5,pady=5)
window.mainloop()




